server:
  port: 8084

spring:
  application:
    name: API-GATEWAY-HOLIDAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: HOLIDAY-PACKAGE-SERVICE
          uri: lb://HOLIDAY-PACKAGE-SERVICE
          predicates:
            - Path=/api/holidayPackage/**
          filters:
            - AuthenticationFilter

        - id: DESTINATION-SERVICE
          uri: lb://DESTINATION-SERVICE
          predicates:
            - Path=/api/destinations/**
          filters:
            - AuthenticationFilter

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

