spring:
  application:
    name: destination-service
  datasource:
    url: jdbc:mysql://localhost:3306/destination_microservice?useSSL=false&serverTimeZone=UTC
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/